### ISSUE TITLE
Changes to rev

### ISSUE THREAD

**Issue by ToniCorinne** [sparkfun/Electret_Microphone_Breakout#1]
-Labels on both side of pcb for headers
-Move board/components onto grid
-Add OSHW logo
-Add board name to silk
-Add dimension measures
-Add version number to copper/schematic
-Add your name for schematic/brd file for "Revised by"
-Swap 4-way junction to non
-Update Op-amp to new package
-Update cap to 0603
-Move traces to 45 degrees
-Double check check list
-Add note to schematic for Vcc range

**Comment by ADataDate** [comment]
Updated and resubmitted for QC review.
