### ISSUE TITLE
design review for v20

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/Electret_Microphone_Breakout#2]
1) Is there a SparkFun Logo? [YES]
comment: Yes, but it is the old "text" symbol version, please update to use the device that uses a pretty sparkfun logo as symbol

2) Is the version number correct? [NO]
comment: currently "V.2", should be v20 - notice the lower case v and the no "dot"

3) Is the VCC range clearly labeled? [YES]
comment: Yes, but it it is currently on the incorrect layer, it needs to be on the "info" layer (97) - it's strange to have text objects on the net layer.

4) Have you verified that the BOM in Sparkle is accurate (also checking for PROD_ID, NAME, VALUE, PREFIX)? [NO]
comment: U1 (opamp) is still not correct. It needs to be replaced with the updated version of the device in the library

5) Is there a correct version number in the copper (aligned properly with the edge of the PCB)? [YES]
comment: 20% ratio on version text looks good and passes drc, this isn't such a super strict rule, but we do like to ensure it doesn't look super pudgy. currently at 30% ratio, your "0" is a single blob of copper, it's nice to have the "0" look like an actual "0"

6) Do all packages have NAME and VALUE? [NO]
comment: The MIC package needs >NAME and >VALUE text objects on their correct layers, thanks for helping to clean up the library!

7) Is 'Revised by:' and 'Revisor Name' included in tDocu? [YES]
comment: yes, but please position it directly below the "designed by" text - note this is on the board tdocu layer

**Comment by ADataDate** [comment]
1. updated logo
2. updated version format on schematic 
3. moved VCC range to the info layer
4. Checked the OP-AMP - Looked like it had the correct part but I re-cloned the library and replaced the part anyway. Also double checked Sparkle and the BOM is correct. 
5. reduced ratio on the version number in copper to 20%
6. updated the MIC package to give it a name and value
7. re-positioned the "Revision by" directly under the "Designed by" in the tdocu layer.

**Comment by lewispg228** [comment]
Looks great. Thanks Mary!

**Comment by lewispg228** [comment]
Upon running the checklist for reds, I found one small thing:

1) Does it pass SparkFun DRC? [NO]
comment: There is one clearance error, but it's on the same signal so that's okay, but please approve thanks.

**Comment by ADataDate** [comment]
Fixed issue- passes DRC, pushed changes

**Comment by lewispg228** [comment]
Thanks Mary. Looks good to go.
